title: Pelumi Aderounmu
logo: logoo.jpeg

description: |
  I am a data analyst with experience analysing data using advanced Excel for report automation,
  Power BI for visualisation, and SQL to manage, retrieve, and manipulate data in relational databases.

theme: jekyll-theme-minimal
